### ISSUE TITLE
optimizing traveling time

### ISSUE THREAD

**Issue by OneManArmy93** [Valdecy/Metaheuristic-Local_Search-GRASP#1]
Hello,

Thank you for your work.
I was wondering if it is faisable t ouse your work to optimize traveling time? in other words, instead of using distance between two points I use traveling time (changing the distance matrix perhaps?)
Thank you

**Comment by Valdecy** [comment]
Hello! Sorry for the late response. Just use the travel time instead of the distance matrix and you're good to go
